apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: api
  template:
    metadata:
      labels:
        app: api
    spec:
      containers:
      - name: api-container
        image: 395714450777.dkr.ecr.us-east-1.amazonaws.com/saude-bi/backend
        imagePullPolicy: Always
        ports:
        - containerPort: 8000
        env:
        - name: DB_HOST
          valueFrom:
            secretKeyRef:
              name: api-secrets
              key: DB_HOST
        - name: DB_PORT
          valueFrom:
            secretKeyRef:
              name: api-secrets
              key: DB_PORT
        - name: DB_USERNAME
          valueFrom:
            secretKeyRef:
              name: api-secrets
              key: DB_USERNAME      
        - name: DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: api-secrets
              key: DB_PASSWORD
        - name: DB_DATABASE
          valueFrom:
            secretKeyRef:
              name: api-secrets
              key: DB_DATABASE
        - name: PORT
          valueFrom:
            secretKeyRef:
              name: api-secrets
              key: PORT
        - name: HOST
          valueFrom:
            secretKeyRef:
              name: api-secrets
              key: HOST
        - name: MODE
          valueFrom:
            secretKeyRef:
              name: api-secrets
              key: MODE 
        - name: JWT_SECRET
          valueFrom:
            secretKeyRef:
              name: api-secrets
              key: JWT_SECRET
        - name: MAINTAINER_CNPJ
          valueFrom:
            secretKeyRef:
              name: api-secrets
              key: MAINTAINER_CNPJ
        - name: DOWNLOAD_PATH
          valueFrom:
            secretKeyRef:
              name: api-secrets
              key: DOWNLOAD_PATH
        - name: REDIS_HOST
          valueFrom:
            secretKeyRef:
              name: api-secrets
              key: REDIS_HOST
        - name: REDIS_PORT
          valueFrom:
            secretKeyRef:
              name: api-secrets
              key: REDIS_PORT      
---
apiVersion: v1
kind: Service
metadata:
  name: api-service
  annotations:
    service.beta.kubernetes.io/aws-load-balancer-type: "nlb"
spec:
  selector:
    app: api
  ports:
  - protocol: TCP
    port: 8000
    targetPort: 8000
  type: LoadBalancer

