apiVersion: apps/v1
kind: Deployment
metadata:
  name: redis-commander-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: redis-commander
  template:
    metadata:
      labels:
        app: redis-commander
    spec:
      containers:
      - name: redis-commander
        image: rediscommander/redis-commander:latest
        ports:
        - containerPort: 8081
        env:
        - name: REDIS_HOSTS
          value: local:redis:6379  

---
apiVersion: v1
kind: Service
metadata:
  name: redis-comander-service
spec:
  selector:
    app: redis
  ports:
  - protocol: TCP
    port: 8081
    targetPort: 8081
